/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans:     ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Stitch design-system tokens — warm amber/cream palette
        'on-surface':                '#271900',
        'primary-fixed':             '#ffdcc6',
        'background':                '#fff8f3',
        'primary-container':         '#b65c00',
        'on-surface-variant':        '#414753',
        'on-error':                  '#ffffff',
        'inverse-surface':           '#3f2d0f',
        'on-secondary':              '#ffffff',
        'on-error-container':        '#93000a',
        'primary':                   '#914800',
        'surface-container':         '#ffebd0',
        'on-secondary-container':    '#756148',
        'on-tertiary-fixed':         '#321200',
        'tertiary-container':        '#bd5700',
        'outline':                   '#717785',
        'tertiary-fixed':            '#ffdbc9',
        'surface-bright':            '#fff8f3',
        'secondary':                 '#6f5b42',
        'primary-fixed-dim':         '#ffb784',
        'on-primary-fixed':          '#301400',
        'on-secondary-fixed-variant':'#56442c',
        'surface-container-high':    '#ffe4be',
        'on-primary-container':      '#fffbff',
        'surface-container-low':     '#fff2e2',
        'secondary-fixed-dim':       '#ddc2a4',
        'on-primary-fixed-variant':  '#713700',
        'secondary-fixed':           '#fadebe',
        'outline-variant':           '#c1c6d5',
        'error-container':           '#ffdad6',
        'inverse-primary':           '#ffb784',
        'tertiary-fixed-dim':        '#ffb68c',
        'tertiary':                  '#964400',
        'surface-container-lowest':  '#ffffff',
        'on-primary':                '#ffffff',
        'surface':                   '#fff8f3',
        'on-tertiary-fixed-variant': '#763400',
        'on-background':             '#271900',
        'on-secondary-fixed':        '#271906',
        'inverse-on-surface':        '#ffeed9',
        'on-tertiary-container':     '#fffbff',
        'secondary-container':       '#fadebe',
        'surface-tint':              '#944a00',
        'surface-dim':               '#f3d6aa',
        'error':                     '#ba1a1a',
        'surface-variant':           '#fcdeb2',
        'surface-container-highest': '#fcdeb2',
        'on-tertiary':               '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
      animation: {
        'shimmer':   'shimmer 2s linear infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
}
