// src/components/CompareBar.tsx
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ShortlistResult } from '../types';
import { RefreshCw, Scale, X } from 'lucide-react';
import { postCompare } from '../api';
import { theme } from '../theme';
import { MapComponent } from './MapComponent';

interface Props {
  shortlist: ShortlistResult;
  requestId: string;
  onReset: () => void;
  isLoading: boolean;
  setIsLoading: (v: boolean) => void;
}

export function CompareBar({ shortlist, requestId, onReset, isLoading, setIsLoading }: Props) {
  const [verdict, setVerdict] = useState<string | null>(null);
  const [showVerdict, setShowVerdict] = useState(false);

  const cars = [
    { car: shortlist.topPick.car,     label: '🏆', color: 'text-amber-300' },
    { car: shortlist.alternative.car, label: '🔄', color: 'text-sky-300' },
    { car: shortlist.surprise.car,    label: '⚡', color: 'text-violet-300' },
  ];

  const handleCompare = async () => {
    if (verdict) { setShowVerdict(true); return; }
    try {
      const { verdict: v } = await postCompare(requestId, setIsLoading);
      setVerdict(v);
      setShowVerdict(true);
    } catch {
      // api.ts already showed the toast
    }
  };

  return (
    <>
      {/* Verdict overlay */}
      <AnimatePresence>
        {showVerdict && verdict && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-end justify-center pb-24 px-4"
            onClick={() => setShowVerdict(false)}
          >
            <motion.div
              initial={{ y: 40, opacity: 0, scale: 0.95 }}
              animate={{ y: 0, opacity: 1, scale: 1 }}
              exit={{ y: 40, opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
              className="w-full max-w-2xl rounded-2xl border border-indigo-500/30 p-6 relative"
              style={{ background: theme.bg.modal, backdropFilter: theme.blur.modal }}
              onClick={(e) => e.stopPropagation()}
            >
              <button
                onClick={() => setShowVerdict(false)}
                className="absolute top-4 right-4 text-zinc-500 hover:text-zinc-300 transition-colors"
              >
                <X size={16} />
              </button>
              <div className="flex items-center gap-2.5 mb-4">
                <div className="w-8 h-8 rounded-lg bg-indigo-500/20 border border-indigo-500/30 flex items-center justify-center">
                  <Scale size={16} className="text-indigo-400" />
                </div>
                <h3 className="text-base font-bold text-white">AI Verdict</h3>
              </div>
              <p className="text-sm text-zinc-300 leading-relaxed">{verdict}</p>
              <p className="text-xs text-zinc-700 mt-4">
                Generated by AI based on your preferences. Always verify with your dealer.
              </p>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Bottom bar */}
      <motion.div
        initial={{ y: 80, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.8, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className="fixed bottom-0 left-0 right-0 z-40"
      >
        <div className="backdrop-blur-2xl border-t border-white/8 px-4 py-3" style={{ background: theme.bg.compareBar }}>
          <div className="max-w-5xl mx-auto flex items-center justify-between gap-4">
            <div className="flex items-center gap-4 sm:gap-6 overflow-x-auto pb-1 flex-1">
              <span className="text-xs text-zinc-600 font-medium flex-shrink-0 hidden sm:inline">Your shortlist:</span>
              <MapComponent
                items={cars}
                keyExtractor={({ car }) => car.id}
                renderItem={({ car, label, color }) => (
                  <div className="flex items-center gap-2 flex-shrink-0">
                    <span className="text-base">{label}</span>
                    <div>
                      <p className={`text-xs font-semibold ${color}`}>{car.brand} {car.model}</p>
                      <p className="text-xs text-zinc-600">₹{car.price_min_lakh.toFixed(1)}–{car.price_max_lakh.toFixed(1)}L</p>
                    </div>
                  </div>
                )}
              />
            </div>
            <div className="flex items-center gap-2 flex-shrink-0">
              <button
                id="compare-btn"
                onClick={handleCompare}
                disabled={isLoading}
                className="flex items-center gap-2 px-4 py-2 rounded-xl border border-indigo-500/30 bg-indigo-500/10 text-indigo-300 text-xs font-medium hover:bg-indigo-500/20 hover:border-indigo-500/50 transition-all disabled:opacity-50"
              >
                {isLoading
                  ? <span className="w-3 h-3 border-2 border-indigo-400/30 border-t-indigo-400 rounded-full animate-spin block" />
                  : <Scale size={12} />}
                {isLoading ? 'Comparing...' : 'Compare'}
              </button>
              <button
                id="start-over-btn"
                onClick={onReset}
                className="flex items-center gap-2 px-4 py-2 rounded-xl border border-white/10 bg-white/5 text-zinc-400 text-xs font-medium hover:text-white hover:border-white/20 transition-all"
              >
                <RefreshCw size={12} />
                <span className="hidden sm:inline">Start over</span>
              </button>
            </div>
          </div>
        </div>
      </motion.div>
    </>
  );
}
