// src/components/CompareBar.tsx
import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ShortlistResult } from '../types';
import { RefreshCw, ArrowLeftRight, X, Plus, Scale } from 'lucide-react';
import { postCompare } from '../api';
import { theme } from '../theme';
import { MapComponent } from './MapComponent';

interface Props {
  shortlist: ShortlistResult;
  requestId: string;
  onReset: () => void;
  isLoading: boolean;
  setIsLoading: (v: boolean) => void;
}

export function CompareBar({ shortlist, requestId, onReset, isLoading, setIsLoading }: Props) {
  const [verdict, setVerdict] = useState<string | null>(null);
  const [showVerdict, setShowVerdict] = useState(false);

  const cars = [
    { car: shortlist.topPick.car,     label: 'Top Match' },
    { car: shortlist.alternative.car, label: 'Alternative' },
    { car: shortlist.surprise.car,    label: 'Surprise Pick' },
  ];

  const handleCompare = async () => {
    if (verdict) { setShowVerdict(true); return; }
    try {
      const { verdict: v } = await postCompare(requestId, setIsLoading);
      setVerdict(v);
      setShowVerdict(true);
    } catch {
      // api.ts already showed the toast
    }
  };

  return (
    <>
      {/* Verdict modal overlay */}
      <AnimatePresence>
        {showVerdict && verdict && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-end justify-center pb-28 px-4"
            onClick={() => setShowVerdict(false)}
          >
            <motion.div
              initial={{ y: 40, opacity: 0, scale: 0.95 }}
              animate={{ y: 0, opacity: 1, scale: 1 }}
              exit={{ y: 40, opacity: 0, scale: 0.95 }}
              transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
              className="w-full max-w-2xl rounded-2xl border border-outline-variant p-6 relative shadow-xl"
              style={{ background: theme.bg.modal, backdropFilter: theme.blur.modal }}
              onClick={(e) => e.stopPropagation()}
            >
              <button
                onClick={() => setShowVerdict(false)}
                className="absolute top-4 right-4 text-on-surface-variant hover:text-on-surface transition-colors"
              >
                <X size={16} />
              </button>
              <div className="flex items-center gap-2.5 mb-4">
                <div className="w-8 h-8 rounded-lg bg-primary/10 border border-primary/20 flex items-center justify-center">
                  <Scale size={16} className="text-primary" />
                </div>
                <h3 className="text-base font-bold text-on-surface font-headline">AI Verdict</h3>
              </div>
              <p className="text-sm text-on-surface-variant leading-relaxed font-body">{verdict}</p>
              <p className="text-xs text-on-surface-variant/60 mt-4">
                Generated by AI based on your preferences. Always verify with your dealer.
              </p>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Sticky comparison drawer */}
      <motion.div
        initial={{ y: 80, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.8, duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className="fixed bottom-0 left-0 md:left-64 right-0 bg-surface-container-lowest border-t border-outline-variant shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.05)] p-4 z-40"
      >
        <div className="max-w-6xl mx-auto flex items-center justify-between gap-4">
          {/* Car thumbnails */}
          <div className="flex items-center gap-4 flex-1 overflow-x-auto pb-1">
            <div className="hidden sm:block text-sm font-label font-bold text-on-surface uppercase tracking-wider mr-2 flex-shrink-0">
              Compare<br />Selection
            </div>
            <div className="flex gap-2">
              <MapComponent
                items={cars}
                keyExtractor={({ car }) => car.id}
                renderItem={({ car }) => (
                  <div className="relative w-16 h-12 rounded-md overflow-hidden border-2 border-primary flex-shrink-0">
                    <img
                      src={car.image_url}
                      alt={`${car.brand} ${car.model}`}
                      className="w-full h-full object-cover"
                      onError={(e) => {
                        (e.target as HTMLImageElement).style.display = 'none';
                      }}
                    />
                    <button className="absolute top-0 right-0 bg-error text-on-error w-4 h-4 flex items-center justify-center rounded-bl-sm">
                      <X size={10} />
                    </button>
                  </div>
                )}
              />
              <div className="w-16 h-12 rounded-md border-2 border-outline-variant relative opacity-50 bg-surface-container flex items-center justify-center flex-shrink-0">
                <Plus size={16} className="text-outline" />
              </div>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2 flex-shrink-0">
            <button
              id="compare-btn"
              onClick={handleCompare}
              disabled={isLoading}
              className="flex items-center gap-2 px-6 py-2 rounded-lg bg-primary text-on-primary font-label font-semibold text-sm hover:bg-primary/90 transition-colors disabled:opacity-50"
            >
              {isLoading
                ? <span className="w-3 h-3 border-2 border-on-primary/30 border-t-on-primary rounded-full animate-spin block" />
                : <ArrowLeftRight size={14} />}
              <span className="hidden sm:inline">{isLoading ? 'Comparing...' : 'Detailed Comparison'}</span>
            </button>
            <button
              id="start-over-btn"
              onClick={onReset}
              className="flex items-center gap-2 px-4 py-2 rounded-lg border border-outline-variant bg-surface text-on-surface text-xs font-medium hover:bg-surface-container transition-all"
            >
              <RefreshCw size={12} />
              <span className="hidden sm:inline">Start over</span>
            </button>
          </div>
        </div>
      </motion.div>
    </>
  );
}
