import { Injectable } from '@nestjs/common';

@Injectable()
export class ConstantsService {
  private readonly DEFAULT_API_URL = 'http://localhost:5173';
  private readonly DEFAULT_PORT = 3001;
  private readonly DB_FILENAME = 'shortlist.db';
  private readonly DEFAULT_DB_DIR = 'data';

  // API Status & Responses
  public readonly SUCCESS_MSG_INTAKE = 'Intake processed successfully';
  public readonly SUCCESS_MSG_CLARIFY = 'Clarifier generated successfully';
  public readonly SUCCESS_MSG_SHORTLIST = 'Shortlist generated successfully';
  public readonly SUCCESS_MSG_COMPARE = 'Compare verdict generated successfully';

  // SSE Stream stages & messages
  public readonly STAGE_ANALYZING = 'analyzing';
  public readonly MSG_ANALYZING = 'Reading between the lines...';

  public readonly STAGE_PERSONA = 'persona';
  public readonly MSG_PERSONA = 'Building your buyer profile...';

  public readonly STAGE_PARSED = 'parsed';
  public readonly MSG_PARSED = 'Got it! Analysing your situation...';
  
  public readonly STAGE_CLARIFYING = 'clarifying';
  public readonly MSG_CLARIFYING = 'One quick question…';
  
  public readonly STAGE_RETRIEVING = 'retrieving';
  public readonly MSG_RETRIEVING = 'Searching 18+ cars for the best matches…';
  
  public readonly STAGE_RANKING = 'ranking';
  public readonly MSG_RANKING = 'Ranking your shortlist…';

  public readonly STAGE_DONE = 'done';
  public readonly MSG_DONE = 'Your shortlist is ready!';

  // Errors
  public readonly ERR_VALIDATION = 'Validation failed';
  public readonly ERR_SESSION_NOT_FOUND = 'Session not found';
  public readonly ERR_PARSED_DATA_MISSING = 'Parsed data missing — call /api/intake first';
  public readonly ERR_PARSED_DATA_MISSING_SHORTLIST = 'Parsed data missing';
  public readonly ERR_SHORTLIST_MISSING = 'Shortlist not found — call /api/shortlist first';
  public readonly ERR_CLARIFY_NOT_READY = 'Clarify question not generated by graph yet.';
  public readonly ERR_AI_UNAVAILABLE = 'AI service is unavailable. Cannot generate clarification questions.';

  public readonly MAX_CLARIFY_QUESTIONS = 5;

  // Rate limiting (TTL in milliseconds)
  public readonly THROTTLE_TTL_MS       = 60_000;  // 1 minute window
  public readonly THROTTLE_INTAKE_LIMIT = 10;      // intake is expensive — AI parse + session
  public readonly THROTTLE_CLARIFY_LIMIT = 30;
  public readonly THROTTLE_SHORTLIST_LIMIT = 30;
  public readonly THROTTLE_COMPARE_LIMIT  = 10;
  public readonly MSG_MORE_CLARIFICATION = 'More context needed';
  public readonly MSG_CLARIFYING_NEXT = 'Got it! One more thing…';

  // Environment variables retrieval logic
  getFrontendUrl(): string {
    const val = process.env.FRONTEND_URL;
    if (val) return val;
    return this.DEFAULT_API_URL;
  }

  getPort(): number {
    const val = process.env.PORT;
    if (val) return parseInt(val, 10);
    return this.DEFAULT_PORT;
  }

  getDbDir(): string {
    const val = process.env.DB_DIR;
    if (val) return val;
    return this.DEFAULT_DB_DIR;
  }

  getDbFilename(): string {
    return this.DB_FILENAME;
  }

  isLangSmithEnabled(): boolean {
    return process.env.LANGCHAIN_TRACING_V2 === 'true' && !!process.env.LANGCHAIN_API_KEY;
  }

  getGeminiServiceCredentials(): any {
    const jsonStr = process.env.GEMINI_SERVICE_JSON;
    if (!jsonStr) {
      console.warn('⚠️ GEMINI_SERVICE_JSON is not defined in environment!');
      return null;
    }
    try {
      return JSON.parse(jsonStr);
    } catch (e) {
      console.error('⚠️ Failed to parse GEMINI_SERVICE_JSON:', e);
      return null;
    }
  }
}
